### ISSUE TITLE
Complete making Progress screen generic

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#10] opened 2020-10-08 03:59 UTC
I turned the brew progress screen into a generic process progress screen. We need to do the following:

1. Pressing the abort button has weird behavior, look into that.
2. The GUI file needs to be updated with generic names for the buttons.
3. The cleaning process needs to utilize the new generic progress screen. As it is, it should be as simple as starting a cleaning process and moving to the process status screen.
4. The "flush system" process needs to be implemented in the UI, it can probably use the same menu as the start cleaning button.
5. The "abort" code in the process status screen needs to be changed to "stop process"

**Comment by TCTaco** [comment] 2020-10-08 05:29
1. Should be resolved as of https://github.com/drmwve/Capstone-Project/commit/a9cc87e519c9b7d485ca3d0119835a6f394dbac2

**Comment by TCTaco** [comment] 2020-10-08 05:53
2. Is resolved with https://github.com/drmwve/Capstone-Project/commit/3e9d58e0f86edbbb4175fe35cdef8ad485f0fb72

**Comment by TCTaco** [comment] 2020-10-08 18:24
3. Is resolved with https://github.com/drmwve/Capstone-Project/commit/8d23116b40588480e2964988141ee8c1098f95fa, https://github.com/drmwve/Capstone-Project/commit/9f6542f158dbfaaf19ae42ce715f97fae3d6a604, and https://github.com/drmwve/Capstone-Project/commit/6222746efa9ddf30cfc3c1cee958f88fd52bf778

4. Is also resolved with https://github.com/drmwve/Capstone-Project/commit/6222746efa9ddf30cfc3c1cee958f88fd52bf778, and https://github.com/drmwve/Capstone-Project/commit/e5b83f57e95cd34e8a4b651054af486a8cf2dd8c

**Comment by TCTaco** [comment] 2020-10-08 18:31
With 5, do you just want the button to say stop process or do you want all the code elements renamed? The function for aborting/stopping a process is using the new generic naming but I still just call it "Abort Process".

If that's ok then the issue is complete, otherwise let me know specifically what you meant with 5 and I can finish it off.

**Comment by drmwve** [comment] 2020-10-08 18:58
> With 5, do you just want the button to say stop process or do you want all the code elements renamed? The function for aborting/stopping a process is using the new generic naming but I still just call it "Abort Process".
> 
> If that's ok then the issue is complete, otherwise let me know specifically what you meant with 5 and I can finish it off.

Both, just so there's consistency in what each command is called across the code. Good work on everything though, thank you!

**Comment by TCTaco** [comment] 2020-10-08 20:19
5. should be resolved with https://github.com/drmwve/Capstone-Project/commit/21934f1b7daf272c86f22b17a963b841cc8dc42f

**Closed as completed by TCTaco** 2020-10-08 20:19 UTC
Labels: enhancement
